<?php
/**
 * Plugin Name: System rezerwacji lotów tandemowych
 * Description: Plugin do rezerwacji lotów tandemowych w WooCommerce.
 * Version: 1.1
 * Author: Autogenerated
 */

if (!defined('ABSPATH')) {exit;}

define('SRL_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('SRL_PLUGIN_URL', plugin_dir_url(__FILE__));

// Validation system
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Config.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Validator.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Formatter.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Database_Manager.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Event_System.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_AJAX_Controllers.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Flight_Manager.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Schedule_Manager.php';
require_once SRL_PLUGIN_DIR . 'includes/validation/SRL_Voucher_Manager.php';

// Core includes
require_once SRL_PLUGIN_DIR . 'includes/database/database-setup.php';
require_once SRL_PLUGIN_DIR . 'includes/email-functions.php';
require_once SRL_PLUGIN_DIR . 'includes/historia-functions.php';

// Admin includes
require_once SRL_PLUGIN_DIR . 'includes/admin/admin-menu.php';
require_once SRL_PLUGIN_DIR . 'includes/admin/admin-calendar.php';
require_once SRL_PLUGIN_DIR . 'includes/admin/admin-day.php';
require_once SRL_PLUGIN_DIR . 'includes/admin/admin-vouchers.php';
require_once SRL_PLUGIN_DIR . 'includes/admin/admin-flights.php';

// Frontend includes
require_once SRL_PLUGIN_DIR . 'includes/frontend/frontend-shortcodes.php';

// Feature includes
require_once SRL_PLUGIN_DIR . 'includes/cart-flight-options.php';
require_once SRL_PLUGIN_DIR . 'includes/product-flight-options.php';
require_once SRL_PLUGIN_DIR . 'includes/client-account.php';
require_once SRL_PLUGIN_DIR . 'includes/woocommerce-integration.php';

// AJAX includes
require_once SRL_PLUGIN_DIR . 'includes/ajax/admin-ajax.php';
require_once SRL_PLUGIN_DIR . 'includes/ajax/frontend-ajax.php';
require_once SRL_PLUGIN_DIR . 'includes/ajax/voucher-ajax.php';
require_once SRL_PLUGIN_DIR . 'includes/ajax/flight-options-ajax.php';

register_activation_hook(__FILE__, 'srl_aktywacja_wtyczki');
register_deactivation_hook(__FILE__, function() {
    wp_clear_scheduled_hook('srl_sprawdz_przeterminowane_loty');
});

function srl_utworz_kategorie_produktow() {
    if (!term_exists('loty-tandemowe', 'product_cat')) {
        wp_insert_term('Loty tandemowe', 'product_cat', array(
            'description' => 'Produkty lotów tandemowych',
            'slug' => 'loty-tandemowe'
        ));
    }
}

function srl_utworz_strone_rezerwacji() {
    $strona_istnieje = get_page_by_path('rezerwuj-lot');
    if (!$strona_istnieje) {
        $strona_id = wp_insert_post(array(
            'post_title' => 'Rezerwuj lot',
            'post_content' => '[srl_kalendarz]',
            'post_status' => 'publish',
            'post_type' => 'page',
            'post_name' => 'rezerwuj-lot'
        ));
        update_option('srl_strona_rezerwacji_id', $strona_id);
    }
}

add_action('wp_enqueue_scripts', function() {
    if (is_user_logged_in()) {
        wp_enqueue_script('srl-flight-options', SRL_PLUGIN_URL . 'assets/js/flight-options-unified.js', array('jquery'), '1.0', true);
        wp_localize_script('srl-flight-options', 'srlFrontend', array(
            'ajaxurl' => admin_url('admin-ajax.php'),
            'nonce' => wp_create_nonce('srl_frontend_nonce'),
            'productIds' => srl_get_flight_option_product_ids()
        ));
    }
});